// filepath: constants/NavigationConfig.ts
import { NavigationItem } from '@/types/navigation';
/**
 * Tourism CMS Navigation Configuration
 * Based on NAGA VENTURE RBAC Documentation
 * Implements hierarchical sidebar with expandable sections
 */
export const tourismAdminNavigation: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    type: 'single',
    path: '/(sidebar)/dashboard',
    permissions: [
      'tourism_admin',
      'business_listing_manager',
      'tourism_content_manager',
      'business_registration_manager',
    ],
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: 'users',
    type: 'dropdown',
    permissions: [
      'tourism_admin',
      'business_registration_manager',
      'business_listing_manager',
    ],
    subsections: [
      {
        id: 'staff-management',
        label: 'Staff Management',
        icon: 'user-shield',
        type: 'single',
        path: '/(sidebar)/user-management/staff-management',
        permissions: ['tourism_admin'],
      },
      {
        id: 'business-owners',
        label: 'Business Owners',
        icon: 'briefcase',
        type: 'single',
        path: '/(sidebar)/user-management/business-owners',
        permissions: [
          'tourism_admin',
          'business_registration_manager',
          'business_listing_manager',
        ],
      },
      {
        id: 'tourist-accounts',
        label: 'Tourist Accounts',
        icon: 'user',
        type: 'single',
        path: '/(sidebar)/user-management/tourist-accounts',
        permissions: ['tourism_admin'],
      },
    ],
  },
  {
    id: 'business-management',
    label: 'Business Management',
    icon: 'building',
    type: 'dropdown',
    permissions: [
      'tourism_admin',
      'business_listing_manager',
      'business_registration_manager',
    ],
    subsections: [
      {
        id: 'all-businesses',
        label: 'All Businesses',
        icon: 'building',
        type: 'single',
        path: '/(sidebar)/business-management/business-listings/all-businesses',
        permissions: ['tourism_admin', 'business_listing_manager'],
      },
      {
        id: 'business-analytics',
        label: 'Business Analytics',
        icon: 'chart-bar',
        type: 'single',
        path: '/(sidebar)/business-management/business-analytics',
        permissions: ['tourism_admin', 'business_listing_manager'],
      },
      {
        id: 'business-registrations',
        label: 'Business Registrations',
        icon: 'clipboard-check',
        type: 'single',
        path: '/(sidebar)/business-management/business-registrations',
        permissions: ['tourism_admin', 'business_registration_manager'],
        badge: { count: 8, type: 'warning' },
      },
    ],
  },
  {
    id: 'tourism-content',
    label: 'Tourism Content',
    icon: 'map',
    type: 'dropdown',
    permissions: ['tourism_admin', 'tourism_content_manager'],
    subsections: [
      {
        id: 'tourist-spots',
        label: 'Tourist Spots',
        icon: 'map-pin',
        type: 'single',
        path: '/(sidebar)/tourism-content/tourist-spots',
        permissions: ['tourism_admin', 'tourism_content_manager'],
      },
      {
        id: 'events-management',
        label: 'Events Management',
        icon: 'calendar',
        type: 'single',
        path: '/(sidebar)/tourism-content/events-management',
        permissions: ['tourism_admin', 'tourism_content_manager'],
      },
      {
        id: 'promotions',
        label: 'Promotions',
        icon: 'gift',
        type: 'single',
        path: '/(sidebar)/tourism-content/promotions',
        permissions: ['tourism_admin', 'tourism_content_manager'],
      },
    ],
  },
  {
    id: 'content-management',
    label: 'Content Management',
    icon: 'file-text',
    type: 'dropdown',
    permissions: [
      'tourism_admin',
      'tourism_content_manager',
      'business_listing_manager',
    ],
    subsections: [
      {
        id: 'content-approval',
        label: 'Content Approval',
        icon: 'check-circle',
        type: 'single',
        path: '/(sidebar)/content-management/content-approval',
        permissions: [
          'tourism_admin',
          'tourism_content_manager',
          'business_listing_manager',
        ],
      },
      {
        id: 'reviews-ratings',
        label: 'Reviews & Ratings',
        icon: 'star',
        type: 'single',
        path: '/(sidebar)/content-management/reviews-ratings',
        permissions: [
          'tourism_admin',
          'tourism_content_manager',
          'business_listing_manager',
        ],
      },
    ],
  },
  {
    id: 'categories',
    label: 'Categories',
    icon: 'tag',
    type: 'dropdown',
    permissions: [
      'tourism_admin',
      'tourism_content_manager',
      'business_listing_manager',
    ],
    subsections: [
      {
        id: 'category-management',
        label: 'Category Management',
        icon: 'tag',
        type: 'single',
        path: '/(sidebar)/categories/category-management',
        permissions: [
          'tourism_admin',
          'tourism_content_manager',
          'business_listing_manager',
        ],
      },
    ],
  },
  {
    id: 'bookings-finance',
    label: 'Bookings & Finance',
    icon: 'credit-card',
    type: 'dropdown',
    permissions: ['tourism_admin'],
    subsections: [
      {
        id: 'booking-management',
        label: 'Booking Management',
        icon: 'calendar-check',
        type: 'single',
        path: '/(sidebar)/bookings-finance/booking-management',
        permissions: ['tourism_admin'],
      },
      {
        id: 'financial-overview',
        label: 'Financial Overview',
        icon: 'dollar-sign',
        type: 'single',
        path: '/(sidebar)/bookings-finance/financial-overview',
        permissions: ['tourism_admin'],
      },
    ],
  },
  {
    id: 'analytics-reporting',
    label: 'Analytics & Reporting',
    icon: 'bar-chart',
    type: 'dropdown',
    permissions: [
      'tourism_admin',
      'business_listing_manager',
      'business_registration_manager',
    ],
    subsections: [
      {
        id: 'platform-analytics',
        label: 'Platform Analytics',
        icon: 'trending-up',
        type: 'single',
        path: '/(sidebar)/analytics-reporting/platform-analytics',
        permissions: ['tourism_admin'],
      },
      {
        id: 'tourism-analytics',
        label: 'Tourism Analytics',
        icon: 'map-pin',
        type: 'single',
        path: '/(sidebar)/analytics-reporting/tourism-analytics',
        permissions: ['tourism_admin'],
      },
      {
        id: 'registration-analytics',
        label: 'Registration Analytics',
        icon: 'user-plus',
        type: 'single',
        path: '/(sidebar)/analytics-reporting/registration-analytics',
        permissions: ['tourism_admin', 'business_registration_manager'],
      },
      {
        id: 'business-analytics-detail',
        label: 'Business Analytics Detail',
        icon: 'bar-chart-2',
        type: 'single',
        path: '/(sidebar)/analytics-reporting/business-analytics-detail',
        permissions: ['tourism_admin', 'business_listing_manager'],
      },
    ],
  },
  {
    id: 'system-administration',
    label: 'System Administration',
    icon: 'settings',
    type: 'dropdown',
    permissions: ['tourism_admin'],
    subsections: [
      {
        id: 'system-settings',
        label: 'System Settings',
        icon: 'sliders',
        type: 'single',
        path: '/(sidebar)/system-administration/system-settings',
        permissions: ['tourism_admin'],
      },
      {
        id: 'api-management',
        label: 'API Management',
        icon: 'server',
        type: 'single',
        path: '/(sidebar)/system-administration/api-management',
        permissions: ['tourism_admin'],
      },
      {
        id: 'security-backup',
        label: 'Security & Backup',
        icon: 'shield',
        type: 'single',
        path: '/(sidebar)/system-administration/security-backup',
        permissions: ['tourism_admin'],
      },
    ],
  },
];
